### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by luminous8** [joelgriffith/browserless#84] opened 2018-10-17 11:17 UTC
Hey,

I've an issue with a website when I try to load it in my debugger but it works in the [browserless debugger ](https://chrome.browserless.io/?script=module.exports%20%3D%20async%20(%7B%20page%20%7D)%20%3D%3E%20%7B%0A%20%20page.emulate(%7B%0A%20%20viewport%3A%20%7B%0A%20%20%20%20%27width%27%3A%201440%2C%0A%20%20%20%20%27height%27%3A%20800%2C%0A%20%20%20%20%27deviceScaleFactor%27%3A%202%2C%0A%20%20%20%20%27isMobile%27%3A%20false%2C%0A%20%20%20%20%27hasTouch%27%3A%20false%2C%0A%20%20%20%20%27isLandscape%27%3A%20false%0A%20%20%7D%0A%7D)%3B%0A%20%20await%20page.goto(%27https%3A%2F%2Fww.victoriassecret.com%2F%27)%3B%0Aawait%20page.screenshot(%7B%0A%20%20%20%20path%3A%20%27full.png%27%2C%0A%20%20%20%20fullPage%3A%20true%0A%7D)%0A%20%20%0A%7D%3B%0A%20%20%20%20%20%20)

On MY debugger
<img width="1440" alt="capture d ecran 2018-10-17 a 13 16 01" src="https://user-images.githubusercontent.com/17875165/47082712-d6356a00-d20e-11e8-8198-11a6dc57ae3a.png">

On browserless.io debugger
<img width="1440" alt="capture d ecran 2018-10-17 a 13 14 02" src="https://user-images.githubusercontent.com/17875165/47082725-e0efff00-d20e-11e8-9730-8161532e2c63.png">

I know that's an issue that came from the website, but I'm wondering why I got this error

**Comment by luminous8** [comment] 2018-10-19 05:34
@joelgriffith In London

**Comment by joelgriffith** [comment] 2018-11-13 04:05
@luminous8 do you still have this issue? I'm unable to reproduce locally even when tunneling, so I'm going to close this (feel free to re-open or discuss further, just doing some house keeping)

**Closed by joelgriffith** 2018-11-13 04:05 UTC
Labels: bug, discussion
