### ISSUE TITLE
Could not start Xvfb

### ISSUE THREAD

**Issue by yknx4** [joelgriffith/browserless#95] opened 2018-11-26 22:19 UTC
I am running browserless image on CircleCI, and I'm facing this issue when the image is booting. This seems to have happened sometime recently since it was working properly a few days ago.

```
> browserless-chrome@1.0.0-alpha start /usr/src/app
> node ./build

/usr/src/app/node_modules/xvfb/index.js:84
          throw new Error('Could not start Xvfb.');
          ^

Error: Could not start Xvfb.
    at Xvfb.startSync (/usr/src/app/node_modules/xvfb/index.js:84:17)
    at new ChromeService (/usr/src/app/build/puppeteer-provider.js:21:40)
    at new BrowserlessServer (/usr/src/app/build/browserless-web-server.js:41:30)
    at Object.<anonymous> (/usr/src/app/build/index.js:43:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

**Comment by segnini75** [comment] 2018-11-27 12:54
I can confirm this problem. Probably caused by this commit: #4982f33d81ce9a9d590dcfd503b85a1d57ee338c

**Comment by segnini75** [comment] 2018-11-27 12:58
Launch with env 'ENABLE_XVBF=false' to bypass this error.

**Comment by joelgriffith** [comment] 2018-11-27 16:32
Yup: was just going to say you can turn it off via that env variable. I'll add it to the docker docs today. Curiously: what machine are you running this on? My hope is that this "just works" regardless of what environment you're on.

**Comment by yknx4** [comment] 2018-11-27 16:34
@joelgriffith 
I'm running it in both Amazon ECS Fargate and CircleCI

**Comment by segnini75** [comment] 2018-11-27 18:48
In my case we are using VMware setup with debían flavour. Will send you the
version later.

**Comment by joelgriffith** [comment] 2018-11-28 06:07
OK: PR landed in master that might expose some helpful logs if you set `DEBUG=browserless*,xvfb` as an environment variable when starting.

**Comment by joelgriffith** [comment] 2018-11-30 02:59
I’m going to close this out — however I’d love to see the error messages you folks are getting after the update. Thanks!

**Closed** 2018-11-30 02:59 UTC
Labels: bug
